FROM peridem-base-bionic

## usage:
## 1. build command
## docker build --no-cache -t peridem-clion-bionic -f Dockerfile-peridem-clion-bionic .
## 2. run
## docker run -d --cap-add sys_ptrace -p127.0.0.1:2222:22 --name peridem-clion-bionic-remote peridem-clion-bionic
## 3. set ssh
## ssh-keygen -f "$HOME/.ssh/known_hosts" -R "[localhost]:2222"
## 4. stop
## docker stop peridem-clion-bionic-remote
## 5. ssh credentials (test user)
## user@password 

# Set metadata
LABEL maintainer="Prashant K. Jha <pjha.sci@gmail.com>"
LABEL description="Docker image for clion remote development"

RUN apt-get update --fix-missing \
&&  apt-get upgrade -y --force-yes \
&&  DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes \
    openssh-server rsync gcc-multilib libstdc++-8-dev \
&&  rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/* \
&&  apt-get autoremove -y \
&&  apt-get autoclean -y 

RUN ( \
    echo 'LogLevel DEBUG2'; \
    echo 'PermitRootLogin yes'; \
    echo 'PasswordAuthentication yes'; \
    echo 'Subsystem sftp /usr/lib/openssh/sftp-server'; \
  ) > /etc/ssh/sshd_config_test_clion \
  && mkdir /run/sshd

RUN useradd -m user \
  && yes password | passwd user

RUN usermod -s /bin/bash user

CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config_test_clion"]
