#!/bin/bash

echo "build docker images locally"

docker_user="prashjha"
image_tag="latest"

for file in ./* ; do
  if [[ -d "$file" ]]; then
    directory_name=${file:2}
    image_name=${directory_name}
    echo "building image  ${directory_name}"

		#./check-if-changed ${image_name}
		#retVal=$?
		retVal=0
		if [ $retVal == 0 ]; then
		  echo "Building ${image_name}"
		  docker build --build-arg TAG=${image_tag} -t ${image_name} ${image_name}

		  echo "Deploying image with tag: ${image_tag}"
		  docker tag ${image_name} prashjha/${image_name}:${image_tag}
		  docker push prashjha/${image_name}:${image_tag}
		else
		  echo "No changes for image ${image_name}"
		fi
	fi;
done
