#!/bin/bash

image_name=$1
deploy=$2 # 0 - no, 1 - yes

docker_user="prashjha"
image_tag="latest"

# ./check-if-changed ${image_name}
# retVal=$?
# if [ $retVal == 0 ]; then
echo "Building ${image_name}"
docker build --build-arg TAG=${image_tag} -t ${image_name} ${image_name}

if [ $deploy == 1 ]; then
  docker login --username ${docker_user} --password ${docker_password}
  echo "Deploying image with tag: ${image_tag}"
  docker tag ${image_name} prashjha/${image_name}:${image_tag}
  docker push prashjha/${image_name}:${image_tag}
fi
# else
#   echo "No changes for image ${image_name}"
#   exit 0
# fi
