version: 2.1

executors:
  compiler:
    docker:
      - image: docker:17.06.0-ce-git
    working_directory: ~/repo

jobs:
  angio-base-bionic:
      executor: compiler
      steps:
        - checkout
        - setup_remote_docker:
            reusable: true
            exclusive: true
        - run:
            name: Install bash
            command: apk add --no-cache bash
        - attach_workspace:
            at: /root/repo/
        - run:
            name: Build + deploy image
            command: ./build-and-deploy-image angio-base-bionic
            no_output_timeout: 30m
        - persist_to_workspace:
            root: /root/repo
            paths:
              - branch_cache
      
  angio-base-focal:
      executor: compiler
      steps:
        - checkout
        - setup_remote_docker:
            reusable: true
            exclusive: true
        - run:
            name: Install bash
            command: apk add --no-cache bash
        - attach_workspace:
            at: /root/repo/
        - run:
            name: Build + deploy image
            command: ./build-and-deploy-image angio-base-focal
            no_output_timeout: 30m
        - persist_to_workspace:
            root: /root/repo
            paths:
              - branch_cache
      
  peridem-base-bionic:
      executor: compiler
      steps:
        - checkout
        - setup_remote_docker:
            reusable: true
            exclusive: true
        - run:
            name: Install bash
            command: apk add --no-cache bash
        - attach_workspace:
            at: /root/repo/
        - run:
            name: Build + deploy image
            command: ./build-and-deploy-image peridem-base-bionic
            no_output_timeout: 30m
        - persist_to_workspace:
            root: /root/repo
            paths:
              - branch_cache
      
  peridem-base-focal:
      executor: compiler
      steps:
        - checkout
        - setup_remote_docker:
            reusable: true
            exclusive: true
        - run:
            name: Install bash
            command: apk add --no-cache bash
        - attach_workspace:
            at: /root/repo/
        - run:
            name: Build + deploy image
            command: ./build-and-deploy-image peridem-base-focal
            no_output_timeout: 30m
        - persist_to_workspace:
            root: /root/repo
            paths:
              - branch_cache
      
workflows:
  version: 2
  build-images:
    jobs:
      - angio-base-bionic
      - angio-base-focal
      - peridem-base-bionic
      - peridem-base-focal
