# -------------------------------------------
# Copyright (c) 2021 - 2024 Prashant K. Jha
# -------------------------------------------

ARG UBUNTU_NAME=
FROM prashjha/peridem-base-${UBUNTU_NAME}:latest

# Set metadata
LABEL maintainer="Prashant K. Jha <pjha.sci@gmail.com>"
LABEL description="Docker image for clion remote development"

## usage:
## 1. pull latest docker image
## UBUNTU_NAME=focal && docker pull prashjha/peridem-base-${UBUNTU_NAME}:latest
## 2. build command
## UBUNTU_NAME=focal && docker build --no-cache --build-arg UBUNTU_NAME=${UBUNTU_NAME} --build-arg TAG=latest -t peridem-clion-${UBUNTU_NAME} -f Dockerfile-peridem-clion-use-peridem-base-image-ubuntu-name-arg . 2>&1 | tee log-peridem-clion-use-peridem-base-image-ubuntu-name-arg-${UBUNTU_NAME}.txt
## OR USING CACHE
## UBUNTU_NAME=focal && docker build --build-arg UBUNTU_NAME=${UBUNTU_NAME} --build-arg TAG=latest -t peridem-clion-${UBUNTU_NAME} -f Dockerfile-peridem-clion-use-peridem-base-image-ubuntu-name-arg . 2>&1 | tee log-peridem-clion-use-peridem-base-image-ubuntu-name-arg-${UBUNTU_NAME}.txt
## 3. run
## UBUNTU_NAME=focal && docker run -d --cap-add sys_ptrace -p127.0.0.1:2222:22 --name peridem-clion-remote-${UBUNTU_NAME} peridem-clion-${UBUNTU_NAME}
## 4. set ssh
## ssh-keygen -f "$HOME/.ssh/known_hosts" -R "[localhost]:2222"
## 5. stop
## UBUNTU_NAME=focal && docker stop peridem-clion-remote-${UBUNTU_NAME}
## 6. ssh credentials (test user)
## user@password 
## Try above command with
## UBUNTU_NAME=bionic
## UBUNTU_NAME=focal
## UBUNTU_NAME=jammy
## UBUNTU_NAME=noble

# -----------------------
# setup user (for mpi tests)
# username - user
# password - password
# add only if the user does not exist
# -----------------------
RUN if id user >/dev/null 2>&1; then echo "User 'user' already exists"; else echo "User 'user' does not exist so creating user 'user'" && useradd -m user && yes password | passwd user && usermod -s /bin/bash user; fi

## to change user
## USER user
## WORKDIR /home/user

# -----------------------
# clion essentials
# -----------------------
RUN apt-get update --fix-missing \
&&  apt-get upgrade -y --force-yes \
&&  DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes \
    openssh-server rsync gcc-multilib \
&&  rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/* \
&&  apt-get autoremove -y \
&&  apt-get autoclean -y 

# -----------------------
# clion setup
# -----------------------
RUN ( \
    echo 'LogLevel DEBUG2'; \
    echo 'PermitRootLogin yes'; \
    echo 'PasswordAuthentication yes'; \
    echo 'Subsystem sftp /usr/lib/openssh/sftp-server'; \
  ) > /etc/ssh/sshd_config_test_clion \
  && mkdir /run/sshd

CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config_test_clion"]
